// Generated by gencpp from file RobotCar/voice2robot.msg
// DO NOT EDIT!


#ifndef ROBOTCAR_MESSAGE_VOICE2ROBOT_H
#define ROBOTCAR_MESSAGE_VOICE2ROBOT_H

#include <ros/service_traits.h>


#include <RobotCar/voice2robotRequest.h>
#include <RobotCar/voice2robotResponse.h>


namespace RobotCar
{

struct voice2robot
{

typedef voice2robotRequest Request;
typedef voice2robotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct voice2robot
} // namespace RobotCar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RobotCar::voice2robot > {
  static const char* value()
  {
    return "983f78df28f3a33759c7924630309e9f";
  }

  static const char* value(const ::RobotCar::voice2robot&) { return value(); }
};

template<>
struct DataType< ::RobotCar::voice2robot > {
  static const char* value()
  {
    return "RobotCar/voice2robot";
  }

  static const char* value(const ::RobotCar::voice2robot&) { return value(); }
};


// service_traits::MD5Sum< ::RobotCar::voice2robotRequest> should match
// service_traits::MD5Sum< ::RobotCar::voice2robot >
template<>
struct MD5Sum< ::RobotCar::voice2robotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RobotCar::voice2robot >::value();
  }
  static const char* value(const ::RobotCar::voice2robotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RobotCar::voice2robotRequest> should match
// service_traits::DataType< ::RobotCar::voice2robot >
template<>
struct DataType< ::RobotCar::voice2robotRequest>
{
  static const char* value()
  {
    return DataType< ::RobotCar::voice2robot >::value();
  }
  static const char* value(const ::RobotCar::voice2robotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RobotCar::voice2robotResponse> should match
// service_traits::MD5Sum< ::RobotCar::voice2robot >
template<>
struct MD5Sum< ::RobotCar::voice2robotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RobotCar::voice2robot >::value();
  }
  static const char* value(const ::RobotCar::voice2robotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RobotCar::voice2robotResponse> should match
// service_traits::DataType< ::RobotCar::voice2robot >
template<>
struct DataType< ::RobotCar::voice2robotResponse>
{
  static const char* value()
  {
    return DataType< ::RobotCar::voice2robot >::value();
  }
  static const char* value(const ::RobotCar::voice2robotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTCAR_MESSAGE_VOICE2ROBOT_H
