// Generated by gencpp from file RobotCar/voice2robotResponse.msg
// DO NOT EDIT!


#ifndef ROBOTCAR_MESSAGE_VOICE2ROBOTRESPONSE_H
#define ROBOTCAR_MESSAGE_VOICE2ROBOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RobotCar
{
template <class ContainerAllocator>
struct voice2robotResponse_
{
  typedef voice2robotResponse_<ContainerAllocator> Type;

  voice2robotResponse_()
    : roompoint_check(false)  {
    }
  voice2robotResponse_(const ContainerAllocator& _alloc)
    : roompoint_check(false)  {
  (void)_alloc;
    }



   typedef uint8_t _roompoint_check_type;
  _roompoint_check_type roompoint_check;





  typedef boost::shared_ptr< ::RobotCar::voice2robotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RobotCar::voice2robotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct voice2robotResponse_

typedef ::RobotCar::voice2robotResponse_<std::allocator<void> > voice2robotResponse;

typedef boost::shared_ptr< ::RobotCar::voice2robotResponse > voice2robotResponsePtr;
typedef boost::shared_ptr< ::RobotCar::voice2robotResponse const> voice2robotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RobotCar::voice2robotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RobotCar::voice2robotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RobotCar::voice2robotResponse_<ContainerAllocator1> & lhs, const ::RobotCar::voice2robotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.roompoint_check == rhs.roompoint_check;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RobotCar::voice2robotResponse_<ContainerAllocator1> & lhs, const ::RobotCar::voice2robotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RobotCar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RobotCar::voice2robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RobotCar::voice2robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RobotCar::voice2robotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ea2ec7918d83076fd2ac06b133f6ea";
  }

  static const char* value(const ::RobotCar::voice2robotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ea2ec7918d8307ULL;
  static const uint64_t static_value2 = 0x6fd2ac06b133f6eaULL;
};

template<class ContainerAllocator>
struct DataType< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RobotCar/voice2robotResponse";
  }

  static const char* value(const ::RobotCar::voice2robotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool roompoint_check\n"
;
  }

  static const char* value(const ::RobotCar::voice2robotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roompoint_check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct voice2robotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RobotCar::voice2robotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RobotCar::voice2robotResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "roompoint_check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.roompoint_check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTCAR_MESSAGE_VOICE2ROBOTRESPONSE_H
