// Generated by gencpp from file RobotCar/web2robotRequest.msg
// DO NOT EDIT!


#ifndef ROBOTCAR_MESSAGE_WEB2ROBOTREQUEST_H
#define ROBOTCAR_MESSAGE_WEB2ROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RobotCar
{
template <class ContainerAllocator>
struct web2robotRequest_
{
  typedef web2robotRequest_<ContainerAllocator> Type;

  web2robotRequest_()
    : room_point(0)  {
    }
  web2robotRequest_(const ContainerAllocator& _alloc)
    : room_point(0)  {
  (void)_alloc;
    }



   typedef int32_t _room_point_type;
  _room_point_type room_point;





  typedef boost::shared_ptr< ::RobotCar::web2robotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RobotCar::web2robotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct web2robotRequest_

typedef ::RobotCar::web2robotRequest_<std::allocator<void> > web2robotRequest;

typedef boost::shared_ptr< ::RobotCar::web2robotRequest > web2robotRequestPtr;
typedef boost::shared_ptr< ::RobotCar::web2robotRequest const> web2robotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RobotCar::web2robotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RobotCar::web2robotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RobotCar::web2robotRequest_<ContainerAllocator1> & lhs, const ::RobotCar::web2robotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.room_point == rhs.room_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RobotCar::web2robotRequest_<ContainerAllocator1> & lhs, const ::RobotCar::web2robotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RobotCar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::RobotCar::web2robotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RobotCar::web2robotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RobotCar::web2robotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RobotCar::web2robotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RobotCar::web2robotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RobotCar::web2robotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RobotCar::web2robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bda4dac81e87b974068cf32c26e9399";
  }

  static const char* value(const ::RobotCar::web2robotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bda4dac81e87b97ULL;
  static const uint64_t static_value2 = 0x4068cf32c26e9399ULL;
};

template<class ContainerAllocator>
struct DataType< ::RobotCar::web2robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RobotCar/web2robotRequest";
  }

  static const char* value(const ::RobotCar::web2robotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RobotCar::web2robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 room_point\n"
"\n"
;
  }

  static const char* value(const ::RobotCar::web2robotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RobotCar::web2robotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct web2robotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RobotCar::web2robotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RobotCar::web2robotRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "room_point: ";
    Printer<int32_t>::stream(s, indent + "  ", v.room_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTCAR_MESSAGE_WEB2ROBOTREQUEST_H
