(cl:defpackage RobotCar-srv
  (:use )
  (:export
   "VOICE2ROBOT"
   "<VOICE2ROBOT-REQUEST>"
   "VOICE2ROBOT-REQUEST"
   "<VOICE2ROBOT-RESPONSE>"
   "VOICE2ROBOT-RESPONSE"
   "WEB2ROBOT"
   "<WEB2ROBOT-REQUEST>"
   "WEB2ROBOT-REQUEST"
   "<WEB2ROBOT-RESPONSE>"
   "WEB2ROBOT-RESPONSE"
  ))

