# 巡检路径点配置
waypoints:
  - name: "巡检点A"
    x: 2.12
    y: -0.276
    theta: 0.0 # 使用 0.0 保持一致性

  - name: "巡检点B"
    x: 2.35
    y: 7.69
    theta: 1.57 # 或使用更精确的 1.5708

  - name: "巡检点C"
    x: -8.12
    y: 7.83
    theta: -1.57 # 或使用更精确的 1.5708

  - name: "巡检点D"
    x: 2.35
    y: 7.69
    theta: -1.57 # 或使用更精确的 -1.5708

  - name: "巡检点E"
    x: 2.12
    y: -0.276
    theta: -1.57

  - name: "巡检点F"
    x: 2.16
    y: -8.84
    theta: -1.57

  - name: "巡检点G" # 注意：与最后一个点重名，但这在YAML语法上是允许的
    x: 1.9
    y: -17.1
    theta: 0.0

  - name: "巡检点H"
    x: 2.16
    y: -0.173
    theta: 3.14

  - name: "巡检点I" # 注意：与倒数第三个点重名
    x: 0.0 # 使用 0.0 保持一致性
    y: 0.0 # 使用 0.0 保持一致性
    theta: 0.0

# 注意：上述路径点坐标是相对于map坐标系的
# theta值说明：
# 0.0     = 0度     = 朝向X轴正方向 →
# 1.5708  = 90度    = 朝向Y轴正方向 ↑
# 3.1416  = 180度   = 朝向X轴负方向 ←
# -1.5708 = -90度 = 朝向Y轴负方向 ↓
